apiVersion: v1
kind: Secret
metadata:
  name: {{ template "generator-helm-chart-1.fullname" . }}
  labels:
    app: {{ template "generator-helm-chart-1.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  secret: {{ .Values.config.secret | b64enc }}
